Repository hbakri/django-ninja-crud, pull requests merged in 2023-07, with the labels that each got.

#31 fix: use `pk` instead of `id`
  ninja_crud/tests/test_abstract.py
  ninja_crud/views/delete.py
  ninja_crud/views/retrieve.py
  ninja_crud/views/update.py
Labels: bug

#32 chore: drop support for python `3.7`
  .github/workflows/tests.yml
  README.md
  pyproject.toml
Labels: workflow, maintenance

#33 fix: raise `404` for non-existing `id` on detail views
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_list.py
  ninja_crud/views/create.py
  ninja_crud/views/list.py
Labels: bug

#36 refactor: `params` objects in tests
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
Labels: refactor

#37 docs: update `README.md` for `v0.2.0` release
  README.md
Labels: documentation, maintenance

#39 release: `v0.2.0`
  pyproject.toml
Labels: workflow

#43 refactor!: remove internal `url_name` from views
  example/tests/test_department.py
  example/tests/test_employee.py
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/views/abstract.py
  ninja_crud/views/create.py
  ninja_crud/views/delete.py
  ninja_crud/views/list.py
  ninja_crud/views/retrieve.py
  ninja_crud/views/update.py
  tests/test_app/tests/test_collection.py
  tests/test_app/tests/test_item.py
  tests/test_app/tests/test_user.py
Labels: refactor

#44 fix: `save` and `delete` hooks typing
  ninja_crud/views/create.py
  ninja_crud/views/delete.py
  ninja_crud/views/update.py
Labels: bug

#47 feat: adding `list` type support to testing suite component attributes
  example/tests/test_department.py
  example/tests/test_employee.py
  ninja_crud/tests/__init__.py
  ninja_crud/tests/request_components.py
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  tests/test_app/tests/test_collection.py
  tests/test_app/tests/test_item.py
  tests/test_app/tests/test_user.py
Labels: enhancement

#49 refactor: `test` classes to reduce code duplication
  ninja_crud/tests/__init__.py
  ninja_crud/tests/assertion_helper.py
  ninja_crud/tests/request_composer.py
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/utils.py
Labels: refactor

#52 refactor: renamed `ModelViewSetTest` class attr `model_view_set` to `model_view_set_class`
  example/tests/test_department.py
  example/tests/test_employee.py
  ninja_crud/tests/test_abstract.py
  tests/test_app/tests/test_collection.py
  tests/test_app/tests/test_item.py
  tests/test_app/tests/test_user.py
Labels: refactor

#54 refactor: split `AbstractModelViewTest` and `ModelViewSetTest` class into separate files
  ninja_crud/tests/__init__.py
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_viewset.py
Labels: refactor

#57 refactor: renamed `AbstractModelViewTest` class attr `model_view` to `model_view_class`
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
Labels: refactor

#58 refactor: removed `AbstractModelViewTest` class attr `name`
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/test_viewset.py
Labels: refactor

#60 refactor: removed `AbstractModelViewTest` class attr `client`
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/test_viewset.py
Labels: refactor

#63 chore: add `LOGGING` configuration in test settings
  tests/test_settings.py
Labels: chore

#68 fix: `type` annotation of `model_view_set_class` attribute in `ModelViewSetTest` class
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/test_viewset.py
Labels: bug

#70 feat: introduce `views` and `tests` matching validation
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_matcher.py
  ninja_crud/tests/test_viewset.py
Labels: enhancement

#71 refactor: split `AbstractModelView` and `ModelViewSet` classes into separate files
  ninja_crud/views/__init__.py
  ninja_crud/views/abstract.py
  ninja_crud/views/viewset.py
Labels: refactor

#73 feat: enforce `ModelViewSetTest` subclasses to be also `TestCase` subclasses
  ninja_crud/tests/test_viewset.py
Labels: enhancement

#77 refactor: rename `test_case` attr of `AbstractModelViewTest` class to `model_view_set_test`
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/test_viewset.py
Labels: refactor

#78 refactor: remove `model_view_set_class` and `urls_prefix` attr of `AbstractModelViewTest`
  ninja_crud/tests/test_abstract.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/test_viewset.py
Labels: refactor

#80 refactor: use attribute names for unique test method naming in `ModelViewSetTest`
  ninja_crud/tests/test_viewset.py
Labels: refactor

#81 feat: add `type` verifications for `ModelViewSetTest` class attributes
  ninja_crud/tests/test_viewset.py
Labels: enhancement

#61 refactor: rename `ModelViewSet` class attr `model` to `model_class`
  README.md
  example/views/view_department.py
  example/views/view_employee.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/test_viewset.py
  ninja_crud/views/abstract.py
  ninja_crud/views/create.py
  ninja_crud/views/delete.py
  ninja_crud/views/list.py
  ninja_crud/views/retrieve.py
  ninja_crud/views/update.py
  ninja_crud/views/utils.py
  ninja_crud/views/viewset.py
  tests/test_app/views/view_collection.py
  tests/test_app/views/view_item.py
  tests/test_app/views/view_user.py
Labels: refactor

#84 fix: revert `README.md` changes from PR #61
  README.md
Labels: bug, documentation

#85 feat: introduce `PatchModelView`
  ninja_crud/tests/__init__.py
  ninja_crud/tests/test_patch.py
  ninja_crud/views/__init__.py
  ninja_crud/views/patch.py
  ninja_crud/views/update.py
  tests/test_app/tests/test_collection.py
  tests/test_app/views/view_collection.py
Labels: enhancement

#87 refactor: rename `urls_prefix` attribute to `base_path` in `EmployeeViewSetTest` class
  example/tests/test_department.py
  example/tests/test_employee.py
  ninja_crud/tests/test_create.py
  ninja_crud/tests/test_delete.py
  ninja_crud/tests/test_list.py
  ninja_crud/tests/test_patch.py
  ninja_crud/tests/test_retrieve.py
  ninja_crud/tests/test_update.py
  ninja_crud/tests/test_viewset.py
  tests/test_app/tests/test_collection.py
  tests/test_app/tests/test_item.py
  tests/test_app/tests/test_user.py
Labels: refactor

#89 refactor: rename `validate_urls_prefix` method to `validate_base_path`
  ninja_crud/tests/test_viewset.py
Labels: refactor

#90 feat: add `type` verifications for `ModelViewSet` class attributes
  ninja_crud/tests/test_viewset.py
  ninja_crud/views/viewset.py
Labels: enhancement

#92 docs: integrate project and `django-ninja` logos in `README`
  README.md
  assets/images/django-ninja-crud-cover.ai
  assets/images/django-ninja-crud-cover.png
Labels: documentation

#96 docs: configure `mkdocs` and `mkdocstrings` for documentation generation
  docs/guides/core_concepts.md
  docs/guides/examples.md
  docs/guides/installation.md
  docs/guides/introduction.md
  docs/guides/setup.md
  mkdocs.yml
  pyproject.toml
Labels: documentation, chore

#100 docs: add package `logo` with associated `license` in `assets/images`
  .gitignore
  assets/images/LOGO_LICENSE.md
  assets/images/django-ninja-crud-logo.ai
  assets/images/django-ninja-crud-logo.png
Labels: documentation, chore

#102 chore: update `pre-commit` configuration
  .pre-commit-config.yaml
Labels: maintenance, chore

#104 chore: rename `LICENSE` file to `LICENSE.md`
  LICENSE.md
Labels: chore

#108 docs: remove `mkdocs` and configure `pydoc-markdown` for documentation generation
  .gitignore
  docs/pydoc-markdown.yml
  mkdocs.yml
  pyproject.toml
Labels: documentation, chore

#93 feat: introduce `router_kwargs` to customize django-ninja's `Router` attributes
  ninja_crud/views/abstract.py
  ninja_crud/views/create.py
  ninja_crud/views/delete.py
  ninja_crud/views/list.py
  ninja_crud/views/patch.py
  ninja_crud/views/retrieve.py
  ninja_crud/views/update.py
  tests/views/__init__.py
  tests/views/test_create.py
  tests/views/test_delete.py
  tests/views/test_list.py
  tests/views/test_patch.py
  tests/views/test_retrieve.py
  tests/views/test_update.py
Labels: enhancement
